# Site Settings
title: xXAlphaManXx | 15 yr old Hacker, developer, designer and system admin
email: hello@alphaman.me
description: Techie stuffs, reviews, coding tips, comparisons and more.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://alphaman.me" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: xXAlphaManXx
user_description: 15 yr old Hacker, developer, designer and system admin
disqus_username: xXAlphaManXx

# Social Media
# Remove the item if you don't need it
github_username: smartclash
facebook_username: xXAlphaManXx
twitter_username: xXAlphaManXx
instagram_username: _xalphamanx_
# linkedin_username: linkedin_username
medium_username: xXAlphaManXx

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
